//! Build script: generate Rust types from interactions.openapi.json
//!
//! Reads schemas/interactions.openapi.json and generates serde-compatible
//! Rust structs and enums into OUT_DIR. The generated code is included
//! by src/interactions_types.rs via `include!`.

use std::collections::{BTreeMap, HashSet};
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let schema_path = manifest_dir.join("schemas").join("interactions.openapi.json");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", schema_path.display());

    let raw = fs::read_to_string(&schema_path).expect("failed to read interactions schema");
    let spec: serde_json::Value =
        serde_json::from_str(&raw).expect("failed to parse interactions schema");

    let schemas = &spec["components"]["schemas"];

    // --- Phase 1: Resolve all $ref references into flat definitions ---
    let mut resolved: BTreeMap<String, ResolvedType> = BTreeMap::new();

    for (name, schema) in schemas.as_object().unwrap() {
        if let Some(rt) = resolve_schema(name, schema, schemas, &mut HashSet::new()) {
            resolved.insert(name.clone(), rt);
        }
    }

    // --- Phase 2: Generate Rust code ---
    let mut code = String::new();
    code.push_str("// Auto-generated from schemas/interactions.openapi.json\n");
    code.push_str("// Generated by build.rs — do not edit manually.\n\n");
    code.push_str("#[allow(non_camel_case_types)]\n");
    code.push_str("use serde::{Deserialize, Serialize};\n\n");

    // Collect names that should be enums (oneOf with discriminator)
    let mut generated = HashSet::new();

    // First pass: generate all types
    let mut types_code = String::new();
    for (name, rt) in &resolved {
        if generated.contains(name) {
            continue;
        }
        let deps = collect_deps(name, &resolved, &mut HashSet::new());
        for dep in deps {
            if !generated.contains(&dep) {
                if let Some(dep_rt) = resolved.get(&dep) {
                    types_code.push_str(&generate_type(&dep, dep_rt, &resolved));
                    types_code.push('\n');
                    generated.insert(dep);
                }
            }
        }
        if !generated.contains(name) {
            types_code.push_str(&generate_type(name, rt, &resolved));
            types_code.push('\n');
            generated.insert(name.clone());
        }
    }

    code.push_str(&types_code);

    // Write to OUT_DIR
    let out_path = out_dir.join("interactions_types.rs");
    fs::write(&out_path, code).expect("failed to write generated types");

    // Also write a module file that includes the generated code
    let mod_path = out_dir.join("interactions_types_mod.rs");
    fs::write(
        &mod_path,
        format!(
            "include!(concat!(env!(\"OUT_DIR\"), \"/interactions_types.rs\"));\n"
        ),
    )
    .expect("failed to write mod file");
}

// ---------------------------------------------------------------------------
// Schema resolution
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
enum ResolvedType {
    Object {
        description: Option<String>,
        properties: BTreeMap<String, PropertyType>,
        required: Vec<String>,
    },
    OneOf {
        description: Option<String>,
        variants: Vec<PropertyType>,
        discriminator: Option<String>,
    },
    Enum {
        description: Option<String>,
        values: Vec<String>,
    },
    StringType,
    IntegerType,
    NumberType,
    BooleanType,
    Array {
        items: Box<PropertyType>,
    },
    Ref(String),
}

#[derive(Debug, Clone)]
struct PropertyType {
    variant_name: Option<String>, // for oneOf enum variants (from title)
    variant_tag: Option<String>,  // #[serde(rename)] value from discriminator mapping
    rust_type: String,
    description: Option<String>,
    is_optional: bool,
}

fn resolve_schema(
    name: &str,
    schema: &serde_json::Value,
    all_schemas: &serde_json::Value,
    visited: &mut HashSet<String>,
) -> Option<ResolvedType> {
    if visited.contains(name) {
        return None;
    }
    visited.insert(name.to_string());

    // Handle $ref
    if let Some(ref_path) = schema.get("$ref").and_then(|v| v.as_str()) {
        let ref_name = ref_path.split('/').last().unwrap();
        if let Some(ref_schema) = all_schemas.get(ref_name) {
            return resolve_schema(ref_name, ref_schema, all_schemas, visited);
        }
        return None;
    }

    // Handle allOf (merge first two)
    if let Some(all_of) = schema.get("allOf").and_then(|v| v.as_array()) {
        let mut merged = serde_json::Map::new();
        for part in all_of {
            if let Some(props) = part.get("properties") {
                if let Some(obj) = props.as_object() {
                    for (k, v) in obj {
                        merged.insert(k.clone(), v.clone());
                    }
                }
            }
            if let Some(req) = part.get("required") {
                // handled separately
            }
        }
        let mut schema_obj = serde_json::Map::new();
        schema_obj.insert("type".to_string(), serde_json::Value::String("object".to_string()));
        schema_obj.insert(
            "properties".to_string(),
            serde_json::Value::Object(merged),
        );
        return resolve_schema(
            name,
            &serde_json::Value::Object(schema_obj),
            all_schemas,
            visited,
        );
    }

    // Handle anyOf — treat as String (both ModelOption and AgentOption are anyOf with string variants)
    if schema.get("anyOf").is_some() {
        return Some(ResolvedType::StringType);
    }

    // Handle oneOf (discriminated union)
    if let Some(variants) = schema.get("oneOf").and_then(|v| v.as_array()) {
        let discriminator = schema
            .get("discriminator")
            .and_then(|d| d.get("propertyName"))
            .and_then(|p| p.as_str())
            .map(String::from);

        // Extract mapping: tag value → schema name
        let mapping: BTreeMap<String, String> = schema
            .get("discriminator")
            .and_then(|d| d.get("mapping"))
            .and_then(|m| m.as_object())
            .map(|obj| {
                obj.iter()
                    .map(|(tag, ref_path)| {
                        let name = ref_path
                            .as_str()
                            .unwrap_or("")
                            .split('/')
                            .last()
                            .unwrap_or("")
                            .to_string();
                        (tag.clone(), name)
                    })
                    .collect()
            })
            .unwrap_or_default();

        let mut variant_types = Vec::new();
        for variant in variants {
            // Use title as variant name if present
            let variant_name = variant
                .get("title")
                .and_then(|t| t.as_str())
                .map(String::from);

            if let Some(ref_path) = variant.get("$ref").and_then(|v| v.as_str()) {
                let ref_name = ref_path.split('/').last().unwrap();
                let vname = variant_name.unwrap_or_else(|| ref_name.to_string());
                // Use explicit mapping if available, otherwise derive from variant name
                let tag = if mapping.is_empty() {
                    Some(derive_tag_from_variant(ref_name, name))
                } else {
                    mapping.iter().find(|(_, name)| *name == ref_name).map(|(t, _)| t.clone())
                };
                variant_types.push(PropertyType {
                    variant_name: Some(vname),
                    variant_tag: tag,
                    rust_type: ref_name.to_string(),
                    description: variant
                        .get("description")
                        .and_then(|d| d.as_str())
                        .map(String::from),
                    is_optional: false,
                });
                // Recursively resolve the variant
                if let Some(vs) = all_schemas.get(ref_name) {
                    resolve_schema(ref_name, vs, all_schemas, &mut HashSet::new());
                }
            } else {
                let rust_type = rust_type_from_schema(variant);
                let vname = variant_name.unwrap_or_else(|| {
                    let t = variant
                        .get("type")
                        .and_then(|t| t.as_str())
                        .unwrap_or("Value");
                    format!("{}{}", t[..1].to_uppercase(), &t[1..])
                });
                variant_types.push(PropertyType {
                    variant_name: Some(vname),
                    variant_tag: None,
                    rust_type,
                    description: variant
                        .get("description")
                        .and_then(|d| d.as_str())
                        .map(String::from),
                    is_optional: false,
                });
            }
        }

        return Some(ResolvedType::OneOf {
            description: schema
                .get("description")
                .and_then(|d| d.as_str())
                .map(String::from),
            variants: variant_types,
            discriminator,
        });
    }

    // Handle enum
    if let Some(values) = schema.get("enum").and_then(|v| v.as_array()) {
        let str_values: Vec<String> = values
            .iter()
            .filter_map(|v| v.as_str().map(String::from))
            .collect();
        if !str_values.is_empty() {
            return Some(ResolvedType::Enum {
                description: schema
                    .get("description")
                    .and_then(|d| d.as_str())
                    .map(String::from),
                values: str_values,
            });
        }
    }

    // Handle object
    if schema.get("type").and_then(|v| v.as_str()) == Some("object")
        || schema.get("properties").is_some()
    {
        let mut properties = BTreeMap::new();
        let required: Vec<String> = schema
            .get("required")
            .and_then(|r| r.as_array())
            .map(|arr| arr.iter().filter_map(|v| v.as_str().map(String::from)).collect())
            .unwrap_or_default();

        if let Some(props) = schema.get("properties").and_then(|p| p.as_object()) {
            for (prop_name, prop_schema) in props {
                let rust_type = rust_type_from_schema(prop_schema);
                let is_optional = !required.contains(prop_name);
                properties.insert(
                    prop_name.clone(),
                    PropertyType {
                        variant_name: None,
                        variant_tag: None,
                        rust_type,
                        description: prop_schema
                            .get("description")
                            .and_then(|d| d.as_str())
                            .map(String::from),
                        is_optional,
                    },
                );
            }
        }

        return Some(ResolvedType::Object {
            description: schema
                .get("description")
                .and_then(|d| d.as_str())
                .map(String::from),
            properties,
            required,
        });
    }

    // Handle array
    if schema.get("type").and_then(|v| v.as_str()) == Some("array") {
        if let Some(items) = schema.get("items") {
            let items_type = if let Some(ref_path) = items.get("$ref").and_then(|v| v.as_str()) {
                let ref_name = ref_path.split('/').last().unwrap();
                PropertyType {
                    variant_name: None,
                    variant_tag: None,
                    rust_type: ref_name.to_string(),
                    description: None,
                    is_optional: false,
                }
            } else {
                PropertyType {
                    variant_name: None,
                    variant_tag: None,
                    rust_type: rust_type_from_schema(items),
                    description: None,
                    is_optional: false,
                }
            };
            return Some(ResolvedType::Array {
                items: Box::new(items_type),
            });
        }
    }

    // Primitive types
    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => return Some(ResolvedType::StringType),
        Some("integer") => return Some(ResolvedType::IntegerType),
        Some("number") => return Some(ResolvedType::NumberType),
        Some("boolean") => return Some(ResolvedType::BooleanType),
        _ => {}
    }

    None
}

fn rust_type_from_schema(schema: &serde_json::Value) -> String {
    if let Some(ref_path) = schema.get("$ref").and_then(|v| v.as_str()) {
        return ref_path.split('/').last().unwrap().to_string();
    }

    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => "String".to_string(),
        Some("integer") => "i64".to_string(),
        Some("number") => "f64".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => {
            if let Some(items) = schema.get("items") {
                let inner = rust_type_from_schema(items);
                format!("Vec<{}>", inner)
            } else {
                "serde_json::Value".to_string()
            }
        }
        Some("object") => "serde_json::Value".to_string(),
        _ => "serde_json::Value".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

fn generate_type(
    name: &str,
    rt: &ResolvedType,
    _all_types: &BTreeMap<String, ResolvedType>,
) -> String {
    match rt {
        ResolvedType::Object {
            description,
            properties,
            ..
        } => generate_struct(name, description, properties),
        ResolvedType::OneOf {
            description,
            variants,
            discriminator,
        } => generate_oneof_enum(name, description, variants, discriminator),
        ResolvedType::Enum {
            description,
            values,
        } => generate_string_enum(name, description, values),
        ResolvedType::Array { items } => {
            format!("pub type {} = Vec<{}>;\n", name, items.rust_type)
        }
        ResolvedType::StringType => format!("pub type {} = String;\n", name),
        ResolvedType::IntegerType => format!("pub type {} = i64;\n", name),
        ResolvedType::NumberType => format!("pub type {} = f64;\n", name),
        ResolvedType::BooleanType => format!("pub type {} = bool;\n", name),
        ResolvedType::Ref(ref_name) => {
            format!("pub type {} = {};\n", name, ref_name)
        }
    }
}

fn generate_struct(
    name: &str,
    description: &Option<String>,
    properties: &BTreeMap<String, PropertyType>,
) -> String {
    let mut code = String::new();

    if let Some(desc) = description {
        let trimmed = desc.trim();
        if !trimmed.is_empty() {
            for line in trimmed.lines() {
                let line = line.trim();
                if !line.is_empty() {
                    code.push_str(&format!("/// {}\n", line));
                }
            }
        }
    }

    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str(&format!("pub struct {} {{\n", to_pascal_case(name)));

    for (prop_name, prop) in properties {
        if let Some(desc) = &prop.description {
            let trimmed = desc.trim();
            if !trimmed.is_empty() {
                let short_desc = trimmed.lines().next().unwrap_or("");
                code.push_str(&format!("    /// {}\n", short_desc));
            }
        }
        let rust_name = to_snake_case(prop_name);
        let serde_attr = if prop.is_optional {
            format!(
                "    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n"
            )
        } else {
            String::new()
        };
        let rust_type = if prop.is_optional {
            format!("Option<{}>", prop.rust_type)
        } else {
            prop.rust_type.clone()
        };
        code.push_str(&format!("{}    pub {}: {},\n", serde_attr, rust_name, rust_type));
    }

    code.push_str("}\n");
    code
}

fn generate_oneof_enum(
    name: &str,
    description: &Option<String>,
    variants: &[PropertyType],
    discriminator: &Option<String>,
) -> String {
    let mut code = String::new();

    if let Some(desc) = description {
        for line in desc.lines() {
            code.push_str(&format!("/// {}\n", line));
        }
    }

    let enum_name = to_pascal_case(name);

    if let Some(tag) = discriminator {
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str(&format!("#[serde(tag = \"{}\")]\n", tag));
        code.push_str(&format!("pub enum {} {{\n", enum_name));

        for variant in variants {
            let variant_name = variant
                .variant_name
                .as_deref()
                .map(to_pascal_case)
                .unwrap_or_else(|| to_pascal_case(&variant.rust_type));
            // Use discriminator mapping for the rename value
            if let Some(ref tag_val) = variant.variant_tag {
                code.push_str(&format!("    #[serde(rename = \"{}\")]\n", tag_val));
            }
            // Variant carries the actual data struct (not unit variant)
            code.push_str(&format!("    {}({}),\n", variant_name, variant.rust_type));
        }

        code.push_str("}\n");
    } else {
        // Untagged enum for oneOf without discriminator (like InteractionsInput)
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("#[serde(untagged)]\n");
        code.push_str(&format!("pub enum {} {{\n", enum_name));

        for variant in variants {
            let variant_name = variant
                .variant_name
                .as_deref()
                .map(to_pascal_case)
                .unwrap_or_else(|| to_pascal_case(&variant.rust_type));
            code.push_str(&format!(
                "    {}({}),\n",
                variant_name, variant.rust_type
            ));
        }

        code.push_str("}\n");
    }

    code
}

fn generate_string_enum(
    name: &str,
    description: &Option<String>,
    values: &[String],
) -> String {
    let mut code = String::new();

    if let Some(desc) = description {
        for line in desc.lines() {
            code.push_str(&format!("/// {}\n", line));
        }
    }

    code.push_str(&format!(
        "#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]\n"
    ));
    code.push_str(&format!("#[serde(rename_all = \"SCREAMING_SNAKE_CASE\")]\n"));
    code.push_str(&format!("pub enum {} {{\n", to_pascal_case(name)));

    for value in values {
        let variant = value
            .replace('/', "_")
            .replace('.', "_")
            .replace('-', "_");
        code.push_str(&format!("    {},\n", variant));
    }

    code.push_str("}\n");
    code
}

fn collect_deps(
    name: &str,
    all_types: &BTreeMap<String, ResolvedType>,
    visited: &mut HashSet<String>,
) -> Vec<String> {
    let mut deps = Vec::new();
    if visited.contains(name) {
        return deps;
    }
    visited.insert(name.to_string());

    if let Some(rt) = all_types.get(name) {
        match rt {
            ResolvedType::Object { properties, .. } => {
                for (_, prop) in properties {
                    let type_name = prop.rust_type.replace("Vec<", "").replace('>', "");
                    if all_types.contains_key(&type_name) && !visited.contains(&type_name) {
                        let sub_deps = collect_deps(&type_name, all_types, visited);
                        deps.extend(sub_deps);
                        deps.push(type_name);
                    }
                }
            }
            ResolvedType::OneOf { variants, .. } => {
                for variant in variants {
                    let type_name = &variant.rust_type;
                    if all_types.contains_key(type_name) && !visited.contains(type_name) {
                        let sub_deps = collect_deps(type_name, all_types, visited);
                        deps.extend(sub_deps);
                        deps.push(type_name.clone());
                    }
                }
            }
            ResolvedType::Array { items } => {
                let type_name = items.rust_type.replace("Vec<", "").replace('>', "");
                if all_types.contains_key(&type_name) && !visited.contains(&type_name) {
                    let sub_deps = collect_deps(&type_name, all_types, visited);
                    deps.extend(sub_deps);
                    deps.push(type_name);
                }
            }
            _ => {}
        }
    }

    deps
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == '.' || c == '/' {
            capitalize = true;
        } else if capitalize {
            result.push(c.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    if result.is_empty() {
        s.to_string()
    } else {
        result
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        if c.is_uppercase() {
            if !result.is_empty() && !result.ends_with('_') {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else if c == '-' || c == '.' || c == '/' {
            result.push('_');
        } else {
            result.push(c);
        }
    }
    let name = if result.is_empty() { s.to_string() } else { result };
    // Escape Rust keywords
    match name.as_str() {
        "type" | "enum" | "struct" | "trait" | "impl" | "fn" | "mod" | "use" | "pub"
        | "async" | "await" | "loop" | "if" | "else" | "match" | "move" | "ref"
        | "static" | "dyn" | "where" | "for" | "while" | "let" | "const" | "box"
        | "self" | "super" | "crate" | "return" | "true" | "false" | "in" | "abstract"
        | "become" | "do" | "final" | "macro" | "override" | "priv" | "typeof"
        | "unsized" | "virtual" | "yield" | "extern" => format!("r#{}", name),
        _ => name,
    }
}

/// Derive a serde tag value from a variant name by stripping the parent enum name.
/// E.g., `TextContent` in enum `Content` → `text`, `UserInputStep` in enum `Step` → `user_input`.
fn derive_tag_from_variant(variant_name: &str, parent_enum_name: &str) -> String {
    let stripped = variant_name
        .strip_suffix(parent_enum_name)
        .unwrap_or(variant_name);
    to_snake_case(stripped)
}
