use axum::http::{HeaderMap, HeaderValue};
use reqwest::RequestBuilder;

use crate::config::Protocol;

/// Build a `HeaderMap` with the same logic as `forward_request_headers` but
/// returns the headers directly instead of applying them to a `RequestBuilder`.
///
/// `protocol` determines correlation header mapping:
/// - Anthropic: x-request-id, X-Client-Request-Id → x-claude-code-session-id
/// - OpenAI:   x-request-id, x-claude-code-session-id → X-Client-Request-Id
///
/// x-request-id is NEVER forwarded as-is — it is generated by the upstream.
pub fn forward_request_headers_map(
    api_key: Option<&str>,
    headers: &HeaderMap,
    protocol: Protocol,
) -> HeaderMap {
    let mut out = HeaderMap::new();
    if let Some(key) = api_key {
        out.insert(
            "x-api-key",
            HeaderValue::from_str(key).unwrap_or(HeaderValue::from_static("")),
        );
        out.insert(
            "Authorization",
            HeaderValue::from_str(&format!("Bearer {key}")).unwrap_or(HeaderValue::from_static("")),
        );
    }
    for (name, value) in headers.iter() {
        let name_str = name.as_str();
        if !should_forward_request_header(name_str) {
            continue;
        }
        if api_key.is_some() && is_auth_header(name_str) {
            continue;
        }
        // x-request-id is generated upstream — never forward as-is.
        // X-Client-Request-Id is handled in protocol-specific mapping below.
        if name_str.eq_ignore_ascii_case("x-request-id")
            || name_str.eq_ignore_ascii_case("x-client-request-id")
        {
            continue;
        }
        out.insert(name.clone(), value.clone());
    }

    // Protocol-specific correlation header mapping.
    // The forwarding loop passes x-claude-code-session-id or
    // X-Client-Request-Id through.
    // x-request-id is excluded above — it gets mapped to the
    // upstream's expected header here instead.
    let source = out
        .get("x-claude-code-session-id")
        .or_else(|| headers.get("X-Client-Request-Id"))
        .or_else(|| headers.get("x-request-id"))
        .cloned();
    if let Some(val) = source {
        let target_key = match protocol {
            Protocol::Anthropic => "x-claude-code-session-id",
            Protocol::OpenAi => "X-Client-Request-Id",
        };
        out.insert(target_key, val);
    }

    out
}

/// Forward non-hop-by-hop headers to upstream, with optional auth override.
///
/// When `api_key` is set, auth headers are replaced with the configured key.
/// When `api_key` is None, incoming auth headers are forwarded as-is.
/// Correlation headers are mapped according to `protocol`.
pub fn forward_request_headers(
    mut builder: RequestBuilder,
    headers: &HeaderMap,
    api_key: Option<&str>,
    protocol: Protocol,
) -> RequestBuilder {
    let map = forward_request_headers_map(api_key, headers, protocol);
    for (name, value) in map.iter() {
        builder = builder.header(name.as_str(), value.as_bytes());
    }
    builder
}

pub fn is_auth_header(name: &str) -> bool {
    matches!(
        name.to_ascii_lowercase().as_str(),
        "x-api-key" | "authorization"
    )
}

pub fn should_forward_request_header(name: &str) -> bool {
    !matches!(
        name.to_ascii_lowercase().as_str(),
        "host"
            | "connection"
            | "content-length"
            | "content-type"
            | "transfer-encoding"
            | "te"
            | "trailers"
            | "upgrade"
            | "keep-alive"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::HeaderValue;
    use reqwest::Client;

    #[test]
    fn is_auth_header_detects_variants() {
        assert!(is_auth_header("x-api-key"));
        assert!(is_auth_header("X-API-KEY"));
        assert!(is_auth_header("Authorization"));
        assert!(is_auth_header("authorization"));
        assert!(!is_auth_header("content-type"));
        assert!(!is_auth_header("x-request-id"));
    }

    #[test]
    fn should_forward_excludes_hop_by_hop() {
        assert!(!should_forward_request_header("host"));
        assert!(!should_forward_request_header("Connection"));
        assert!(!should_forward_request_header("Transfer-Encoding"));
        assert!(!should_forward_request_header("Content-Length"));
        assert!(!should_forward_request_header("Content-Type"));
        assert!(!should_forward_request_header("Keep-Alive"));
        assert!(should_forward_request_header("x-request-id"));
        assert!(should_forward_request_header("accept"));
    }

    #[test]
    fn forward_request_headers_applies_auth_override() {
        let client = Client::new();
        let builder = client.get("http://example.com");

        let mut headers = axum::http::HeaderMap::new();
        headers.insert("x-api-key", HeaderValue::from_static("incoming-key"));
        headers.insert(
            "authorization",
            HeaderValue::from_static("Bearer incoming-token"),
        );

        let result =
            forward_request_headers(builder, &headers, Some("override-key"), Protocol::OpenAi);
        let req = result.build().expect("build request");

        assert_eq!(req.headers().get("x-api-key").unwrap(), "override-key");
        assert_eq!(
            req.headers().get("authorization").unwrap(),
            "Bearer override-key"
        );
    }

    #[test]
    fn forward_request_headers_forwards_incoming_auth_when_no_override() {
        let client = Client::new();
        let builder = client.get("http://example.com");

        let mut headers = axum::http::HeaderMap::new();
        headers.insert("x-api-key", HeaderValue::from_static("incoming-key"));

        let result = forward_request_headers(builder, &headers, None, Protocol::Anthropic);
        let req = result.build().expect("build request");

        assert_eq!(req.headers().get("x-api-key").unwrap(), "incoming-key");
    }

    #[test]
    fn forward_request_headers_excludes_x_request_id() {
        let client = Client::new();
        let builder = client.get("http://example.com");

        let mut headers = axum::http::HeaderMap::new();
        headers.insert("x-request-id", HeaderValue::from_static("req-123"));

        let result = forward_request_headers(builder, &headers, Some("key"), Protocol::OpenAi);
        let req = result.build().expect("build request");

        // x-request-id is never forwarded as-is — it's generated by upstream
        assert!(req.headers().get("x-request-id").is_none());
    }

    // ── forward_request_headers_map ─────────────────────────

    fn request_headers_with_auth() -> axum::http::HeaderMap {
        let mut h = axum::http::HeaderMap::new();
        h.insert("x-api-key", HeaderValue::from_static("client-key"));
        h.insert(
            "authorization",
            HeaderValue::from_static("Bearer client-token"),
        );
        h.insert("x-request-id", HeaderValue::from_static("req-1"));
        h.insert("content-type", HeaderValue::from_static("application/json"));
        h
    }

    #[test]
    fn forward_request_headers_map_with_api_key() {
        let result = forward_request_headers_map(
            Some("my-key"),
            &request_headers_with_auth(),
            Protocol::OpenAi,
        );
        // API key overrides auth
        assert_eq!(result.get("x-api-key").unwrap().to_str().unwrap(), "my-key");
        assert_eq!(
            result.get("authorization").unwrap().to_str().unwrap(),
            "Bearer my-key"
        );
        // Client auth is stripped
        assert_eq!(result.get_all("authorization").iter().count(), 1);
        // x-request-id excluded, mapped to X-Client-Request-Id for OpenAI
        assert!(
            result.get("x-request-id").is_none(),
            "x-request-id must NOT be forwarded to any upstream"
        );
        assert_eq!(
            result.get("X-Client-Request-Id").unwrap().to_str().unwrap(),
            "req-1",
            "x-request-id must be mapped to X-Client-Request-Id for OpenAI"
        );
        assert!(
            result.get("content-type").is_none(),
            "content-type must be excluded from forwarding"
        );
    }

    #[test]
    fn forward_request_headers_map_without_api_key() {
        let result =
            forward_request_headers_map(None, &request_headers_with_auth(), Protocol::OpenAi);
        // Client auth forwarded as-is
        assert_eq!(
            result.get("x-api-key").unwrap().to_str().unwrap(),
            "client-key"
        );
        assert_eq!(
            result.get("authorization").unwrap().to_str().unwrap(),
            "Bearer client-token"
        );
        // x-request-id excluded, mapped to X-Client-Request-Id for OpenAI
        assert!(
            result.get("x-request-id").is_none(),
            "x-request-id must NOT be forwarded"
        );
        assert_eq!(
            result.get("X-Client-Request-Id").unwrap().to_str().unwrap(),
            "req-1"
        );
    }

    // ── Protocol-aware correlation mapping ──────────────────

    #[test]
    fn anthropic_maps_x_request_id_to_x_claude_code_session_id() {
        let mut headers = axum::http::HeaderMap::new();
        headers.insert("x-request-id", HeaderValue::from_static("req-456"));
        let result = forward_request_headers_map(None, &headers, Protocol::Anthropic);
        // x-request-id excluded, mapped to x-claude-code-session-id
        assert!(
            result.get("x-request-id").is_none(),
            "x-request-id must NOT be forwarded"
        );
        assert_eq!(
            result
                .get("x-claude-code-session-id")
                .unwrap()
                .to_str()
                .unwrap(),
            "req-456"
        );
    }

    #[test]
    fn anthropic_maps_x_client_request_id_to_x_claude_code_session_id() {
        let mut headers = axum::http::HeaderMap::new();
        headers.insert("X-Client-Request-Id", HeaderValue::from_static("client-1"));
        let result = forward_request_headers_map(None, &headers, Protocol::Anthropic);
        assert!(
            result.get("X-Client-Request-Id").is_none(),
            "X-Client-Request-Id must NOT be forwarded to Anthropic"
        );
        assert_eq!(
            result
                .get("x-claude-code-session-id")
                .unwrap()
                .to_str()
                .unwrap(),
            "client-1"
        );
    }

    #[test]
    fn anthropic_passthrough_x_claude_code_session_id() {
        let mut headers = axum::http::HeaderMap::new();
        headers.insert(
            "x-claude-code-session-id",
            HeaderValue::from_static("session-123"),
        );
        let result = forward_request_headers_map(None, &headers, Protocol::Anthropic);
        assert_eq!(
            result
                .get("x-claude-code-session-id")
                .unwrap()
                .to_str()
                .unwrap(),
            "session-123"
        );
    }

    #[test]
    fn openai_maps_x_claude_code_session_id_to_x_client_request_id() {
        let mut headers = axum::http::HeaderMap::new();
        headers.insert(
            "x-claude-code-session-id",
            HeaderValue::from_static("session-123"),
        );
        let result = forward_request_headers_map(None, &headers, Protocol::OpenAi);
        assert_eq!(
            result.get("X-Client-Request-Id").unwrap().to_str().unwrap(),
            "session-123"
        );
    }

    #[test]
    fn openai_maps_x_request_id_to_x_client_request_id() {
        let mut headers = axum::http::HeaderMap::new();
        headers.insert("x-request-id", HeaderValue::from_static("req-789"));
        let result = forward_request_headers_map(None, &headers, Protocol::OpenAi);
        assert!(
            result.get("x-request-id").is_none(),
            "x-request-id must NOT be forwarded"
        );
        assert_eq!(
            result.get("X-Client-Request-Id").unwrap().to_str().unwrap(),
            "req-789"
        );
    }

    #[test]
    fn openai_x_client_request_id_passthrough() {
        let mut headers = axum::http::HeaderMap::new();
        headers.insert("X-Client-Request-Id", HeaderValue::from_static("client-99"));
        let result = forward_request_headers_map(None, &headers, Protocol::OpenAi);
        // X-Client-Request-Id excluded from generic forwarding but mapped explicitly
        assert_eq!(
            result.get("X-Client-Request-Id").unwrap().to_str().unwrap(),
            "client-99"
        );
    }

    #[test]
    fn anthropic_x_claude_code_session_id_priority_over_x_request_id() {
        let mut headers = axum::http::HeaderMap::new();
        headers.insert("x-request-id", HeaderValue::from_static("req-1"));
        headers.insert(
            "x-claude-code-session-id",
            HeaderValue::from_static("session-1"),
        );
        let result = forward_request_headers_map(None, &headers, Protocol::Anthropic);
        // x-claude-code-session-id is passthrough, x-request-id is excluded
        assert!(result.get("x-request-id").is_none());
        assert_eq!(
            result
                .get("x-claude-code-session-id")
                .unwrap()
                .to_str()
                .unwrap(),
            "session-1"
        );
    }
}
